version: '3.5'
services:
  webapi:
    container_name: opencdn-webapi
    restart: always
    build:
      context: .
      dockerfile: OpenCdn.WebApi/Dockerfile
    networks:
      opencdn:
        ipv4_address: 172.43.2.1
    ports:
      - '8080:8080'
      - '443:443'
  client:
    container_name: opencdn-client
    restart: always
    depends_on:
      - webapi
    build:
      context: .
      dockerfile: OpenCdn.Client/Dockerfile
    networks:
      opencdn:
        ipv4_address: 172.43.1.2
    ports:
      - '4200:4200'
networks:
  opencdn:
    name: opencdn
    driver: bridge
    ipam:
      config:
        - subnet: 172.43.0.0/16